### PR TITLE
Figma RTL

### PR DESCRIPTION
**Pull request by iddan**

### CODE REVIEW

**Review by jackiecorn — COMMENTED** [review]
Nice! Code is perfect.
Please consider adding an image preview of your plugin's experience.

**Comment by jackiecorn** [comment]
Please add a screenshot to your manifest and we will approve the PR. Thanks!

**Comment by iddan** [comment]
Done

**Comment by jackiecorn** [comment]
Congrats on being the first developer to publish a new plugin on Figma Plus!
Please go to our [Spectrum community](https://spectrum.chat/figma-plus/releases?tab=posts) and share your release with everyone!

**Pull request merged**
